# Import the numpy package under the name np

In [2]:
import numpy as np

# Print the numpy version and the configuration

In [3]:
print(np.__version__)
np.show_config()

1.21.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nokia/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nokia/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nokia/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nokia/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nokia/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nokia/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Nokia/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Nokia/anaconda3\\Library\\include']
Supported SIMD extensions in this NumPy insta

# Create a null vector of size 10

In [4]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# Create a null vector of size 10 but the fifth value which is 1

In [5]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# Create a vector with values ranging from 10 to 49

In [6]:
x=np.arange(10,50)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# Reverse a vector

In [7]:
x=np.arange(10)
x=x[::-1]
print(x)

[9 8 7 6 5 4 3 2 1 0]


# Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
x=np.arange(9).reshape(3,3)


print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Find indices of non­zero elements from [1,2,0,0,4,0]

In [12]:
x=np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4], dtype=int64),)


#  Create a 3x3 identity matrix

In [13]:
z=np.eye(3)
print(z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Create a 3x3x3 array with random values

In [15]:
z=np.random.random((3,3,3))
print(z)

[[[0.94942005 0.2275905  0.06388983]
  [0.02155648 0.03200445 0.2683714 ]
  [0.52556356 0.84285338 0.33123728]]

 [[0.4026942  0.62110044 0.77544936]
  [0.10777051 0.84284505 0.73695064]
  [0.57021355 0.35261849 0.95576645]]

 [[0.7297345  0.14542627 0.8783449 ]
  [0.00788336 0.62808242 0.92910725]
  [0.54398724 0.41674804 0.71470594]]]


# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [16]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(z)

[[[0.94942005 0.2275905  0.06388983]
  [0.02155648 0.03200445 0.2683714 ]
  [0.52556356 0.84285338 0.33123728]]

 [[0.4026942  0.62110044 0.77544936]
  [0.10777051 0.84284505 0.73695064]
  [0.57021355 0.35261849 0.95576645]]

 [[0.7297345  0.14542627 0.8783449 ]
  [0.00788336 0.62808242 0.92910725]
  [0.54398724 0.41674804 0.71470594]]]
